"C-j" = "goto_next_buffer"
"C-k" = "goto_previous_buffer"
"C-A-left"  = "jump_view_left"
"C-A-right" = "jump_view_right"
"C-A-up"    = "jump_view_up"
"C-A-down"  = "jump_view_down"
"C-A-h"     = "jump_view_left"
"C-A-l"     = "jump_view_right"
"C-A-k"     = "jump_view_up"
"C-A-j"     = "jump_view_down"
"C-A-S-left"  = "swap_view_left"
"C-A-S-right" = "swap_view_right"
"C-A-S-up"    = "swap_view_up"
"C-A-S-down"  = "swap_view_down"
"C-A-S-h" = "swap_view_left"
"C-A-S-l" = "swap_view_right"
"C-A-S-k" = "swap_view_up"
"C-A-S-j" = "swap_view_down"
K = "hover"
